language: go
go:
- 1.11.x
env:
  global:
  - SSH_KEY="travis_key"
  - GIT_NAME="VigoTech Alliance"
  - GIT_EMAIL="vigotechalliance@gmail.com"
  - SOURCE_DIR="docs"
  - DEPLOY_BRANCH="source"
before_install:
- openssl aes-256-cbc -K $encrypted_35b54c54cbb7_key -iv $encrypted_35b54c54cbb7_iv -in travis_key.enc -out travis_key -d
before_script:
- go get -v github.com/tidwall/gjson
- go get github.com/magefile/mage
- mkdir $HOME/src && cd $HOME/src && git clone https://github.com/gohugoio/hugo.git && cd hugo && go install
script:
- cd ${TRAVIS_HOME}/gopath/src/github.com/VigoTech/vigotech.github.io && go run scripts/vigotech.go
- cd ${TRAVIS_HOME}/gopath/src/github.com/VigoTech/vigotech.github.io && hugo
after_success:
- cd ${TRAVIS_HOME}/gopath/src/github.com/VigoTech/vigotech.github.io && ./scripts/deploy.sh
