baseURL = "https://vigotechalliance.github.io/"
languageCode = "gl-es"
title = "VigoTech"
publishDir = "docs"
theme = "hugoscroll"

[Params]
  github = "VigoTech"
  twitter = "vigotech_"
  email = "grupos@vigotech.org"
  description = "Agregrador dos diferentes meetups de Tecnoloxía en Vigo"
  cover = "/images/porto_low.jpg"
  logo = "/images/logo.png"
