baseURL = "https://vigotech.github.io"
languageCode = "gl-es"
title = "Vigo Tech Alliance"
publishDir = "docs"
theme = "hugoscroll"

[Params]
  github = "VigoTech"
  twitter = "vigotechallianc"
  email = "vigotechalliance@gmail.com"
  description = "Agregrador dos diferentes meetups de Tecnoloxía en Vigo"
  cover = "/images/porto_low.jpg"
  logo = "/images/logo.png"
